In [1]:
# Om Sai Ram

In [5]:
import numpy as np # importing the numpy package

In [9]:
np.__version__ # verifying the installed numpy version

'1.26.4'

In [91]:
type(np)

module

In [10]:
import sys # importing sys module
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

In [12]:
mylist = [1,2,3,4,5] # creating a list
mylist

[1, 2, 3, 4, 5]

In [16]:
type(mylist)

list

In [17]:
arr = np.array(mylist) # changing our list into an array
arr

array([1, 2, 3, 4, 5])

In [18]:
type(arr)

numpy.ndarray

In [19]:
type(mylist)

list

In [21]:
np.arange(10) # returns a range of values from 0 till n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(3.0) # returns a range of float values from 0 till n-1

array([0., 1., 2.])

In [23]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [24]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
np.arange(0,3) # returns a range of values from start index till end index-1 (n-1)

array([0, 1, 2])

In [26]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [27]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [28]:
np.arange(20,10)

array([], dtype=int32)

In [29]:
np.arange(-20,10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [30]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [31]:
np.arange(-20,-10) # returns a range of values from -20 till -11 (end index - 1)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [33]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [34]:
np.arange(10,30,5) # returns a range of values from start index till end index-1 with a step count of 5 (10-start, 30-end, 5-step count)

array([10, 15, 20, 25])

In [35]:
np.arange(2,9,2) # (2 - start index, 9 - end index and 2 - step count )

array([2, 4, 6, 8])

# One dimensional

In [36]:
np.zeros(10) # Parameter Tuning(using default system built parameters) --> zeroes is a built in function which  returns an array of zeroes

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [92]:
np.zeros(10,dtype=int) # Hyper-parameter Tuning (changing the system built parameters bydefault type is float and we're modifying it to int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Two dimensional array

In [38]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [39]:
np.zeros((3,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [41]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [42]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [43]:
np.zeros((10,30),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [44]:
np.zeros((10,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [45]:
np.ones(3)

array([1., 1., 1.])

In [46]:
np.ones(3,dtype=int)

array([1, 1, 1])

## n dimensional array

In [47]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

### rand() function 

In [49]:
rand(5) # invalid as we've not imported the package and module in which the rand() function resides

NameError: name 'rand' is not defined

In [50]:
random.rand(5)

NameError: name 'random' is not defined

## One dimensional array

In [51]:
np.random.rand(5) # returns an array of random values with in the given range 

array([0.66119935, 0.16585658, 0.23821139, 0.62254891, 0.21606648])

In [52]:
np.random.rand(5)

array([0.93159257, 0.60427219, 0.36117226, 0.32863913, 0.05375174])

## n dimensional array


In [54]:
np.random.rand(3,5) # returns an array of random float(default type) values with 3 rows and 5 columns

array([[0.88805893, 0.47126985, 0.82790833, 0.07468047, 0.49946726],
       [0.29370959, 0.76785767, 0.34715375, 0.58608421, 0.72154551],
       [0.98817373, 0.49572922, 0.44418519, 0.6333843 , 0.59822722]])

In [55]:
np.random.rand(2,3) # produces random float values with 2 rows and 3 columns

array([[0.59535738, 0.23227951, 0.98684682],
       [0.80304483, 0.40462308, 0.8166631 ]])

## randint() function

In [95]:
np.random.randint(5) # produces a random value between 0 to 5 excluding 5

0

In [96]:
np.random.randint(5,9) # produces a random value between 5 to 9 excluding 9

5

In [67]:
np.random.randint(4,6) # returns a random number between 4 and 5.. 6 will be excluded as this will consider n-1

5

In [68]:
np.random.randint(2,20)

17

### One dimensional array

In [70]:
np.random.randint(2,20,4)

array([ 8,  3,  8, 18])

In [71]:
np.random.randint(10,20,5)

array([16, 12, 14, 14, 12])

### n dimensional array

In [97]:
np.random.randint(10,40,(10,5)) # produces an array(10x5) of values from 10 till 40(excluding)

array([[36, 34, 16, 11, 10],
       [30, 23, 13, 39, 16],
       [27, 39, 34, 28, 14],
       [28, 18, 30, 39, 11],
       [18, 18, 17, 13, 19],
       [20, 13, 32, 33, 24],
       [12, 36, 27, 26, 10],
       [28, 21, 11, 28, 13],
       [11, 24, 24, 10, 28],
       [37, 25, 33, 22, 30]])

In [98]:
np.arange(1,13) # produces a range of values from 1 to 12(n-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [76]:
np.arange(1,13).reshape(3,4) # produces a range of values from 1 to 12 and reshapes them into an array(3-rows and 4-columns)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [77]:
np.arange(1,13).reshape(5,4) # invalid as the size of values is 12 but the array size (5*4 = 20) exceeds it

ValueError: cannot reshape array of size 12 into shape (5,4)

In [78]:
np.arange(1,13).reshape(6,2) # size of the array 6*2=12 exactly matches with the size of the values - 12

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [79]:
np.arange(1,13).reshape(6,3) # 12 doesnot equals to 6*3 = 18.. so invalid

ValueError: cannot reshape array of size 12 into shape (6,3)

In [80]:
np.arange(1,13).reshape(12,1) # 12 equals to 12*1 = 12

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [81]:
np.arange(1,13).reshape(4,3) # 12 is equal to 4*3 = 12

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [82]:
np.arange(1,13).reshape(4,2) # 12 doesnot equals to 4*2 = 8.. so invalid

ValueError: cannot reshape array of size 12 into shape (4,2)

In [99]:
b = np.random.randint(10,20,(5,4)) # returns an 5x4 array of random values from 10 to 20(excludes 20)
b

array([[16, 15, 10, 14],
       [14, 12, 10, 14],
       [10, 11, 10, 16],
       [17, 14, 16, 10],
       [15, 11, 15, 12]])

In [100]:
type(b) # nd arrray refers to n-dimensional array

numpy.ndarray

In [101]:
b

array([[16, 15, 10, 14],
       [14, 12, 10, 14],
       [10, 11, 10, 16],
       [17, 14, 16, 10],
       [15, 11, 15, 12]])

In [102]:
b[:]

array([[16, 15, 10, 14],
       [14, 12, 10, 14],
       [10, 11, 10, 16],
       [17, 14, 16, 10],
       [15, 11, 15, 12]])

In [103]:
b[1:3]

array([[14, 12, 10, 14],
       [10, 11, 10, 16]])